[variables]
PYTHON_VERSION = '3.7'

[setup]
pkgs = ["python37", "ffmpeg"]

[phases.install]
cmds = ["/usr/bin/python3.7 -m venv /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "/usr/bin/python3.7 -m tg_bot"
